
<div class='header'>
		<ul class="service-bar">
			<li class="service-cell">
				<a href="http://www.battlenet.com.cn/"  title="首页" data-action="Battle.net Home"> </a>
			</li>
			<li class="service-cell">
				<a href="/user/login/" onclick="return Login.open()">登录</a>
				或者
				<a href="/user/register/">注册账号</a>
			</li>
			<li class="service-cell">
				<a class="service-link" href="https://www.battlenet.com.cn/shop/" data-action="Shop">充值</a>
			</li>
			<li class="service-cell">
			<a class="service-link" href="https://www.battlenet.com.cn/account/management/" data-action="Account">客服</a>
			</li>

		</ul>

</div>

<div class='notice'>


</div>
<div class="main">
	<ul class='game-bar'>
		<li class="game-cell">
			<div>
				<a href="/game1">
					<img src="/img/game1.png" alt="Game1" />
					</a>
				<div>
				<a href="/game1">Enter game1...</a>
				</div>
			</div>
		</li>
		
		<li class="game-cell">
			<div>
				<a href="/game2">
					<img src="/img/game2.png">
					</a>
				<div>
				<a href="/game2">Enter game2...</a>
				</div>
			</div>
				</li>
		
		<li class="game-cell">
			<div>
				<a href="/game3">
					<img src="/img/game3.png">
					</a>
				<div>
				<a href="/game3">Enter game3...</a>
				</div>
			</div>
				</li>
	</ul>

</div>
